name: Publish Snap

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
          
      - name: Build and Upload Snap
        working-directory: ./s1panel
        run: |
          echo "Current directory: $(pwd)"
          ls snap || echo "No snap directory found!"
          snapcraft --destructive-mode -v
          SNAP_FILE=$(ls *.snap | head -1)
          
          echo "Built $SNAP_FILE"
          TAG_NAME="${GITHUB_REF##*/}"
          if [[ "$TAG_NAME" =~ ^v[0-9] ]]; then
            CHANNEL="stable"
          else
            CHANNEL="edge"
          fi
          
          echo "Logging in to Snap Store..."
          echo "${{ secrets.SNAPCRAFT_LOGIN }}" > snap-login.json
          snapcraft login --with snap-login.json          
          
          echo "Releasing to: $CHANNEL"
          snapcraft upload "$SNAP_FILE" --release=$CHANNEL
